language: ruby

cache:
  bundler: true

dist: trusty

sudo: false

env:
  global:
  - RUBYOPT='-W0'
  - COVERAGE=1
  matrix:
  - INTEGRATION_SPECS=0
  - INTEGRATION_SPECS=1

matrix:
  include:
    - sudo: required
      dist: trusty
      env:
      script:
        - docker build -t travis-build .
        - docker run -d -it -p 5000:5000 -e PORT=5000 travis-build
        - sleep 10
        - e=0; for f in example_payloads/*.json; do echo ${f##*/}; curl -sf -X POST -d @$f localhost:5000/script >/dev/null || let e=$e+1; done; test $e -eq 0

script:
  - bundle exec rake
  - e=0; for f in examples/*.sh.txt; do echo "checking bash syntax $f"; bash -n $f || let e=$e+1; done; test $e -eq 0
  - |
    e=0
    mkdir -p $HOME/.travis
    for f in examples/*-integration-*.sh.txt; do
      cat > $HOME/.travis/job_stages < /dev/null
      sed -i '/^source $HOME\/\.travis\/job_stages/,$d' $f
      bash --norc -c "source $f && source $HOME/.travis/job_stages || exit 1" || let e=$e+1
    done
    test $e -eq 0

after_success: bundle exec codeclimate-test-reporter

before_deploy: ruby script/build_s3_index_html.rb

deploy:
  provider: s3
  access_key_id:
    secure: "fXt5NG5UGDvpnRFvUUk9J//iSo+Vh28oEUJvjZqiUZ9GRHp5TrIS5vL4bPlD/1RrJRp7BVVj1+4ThXZRzrMhF5xazK8k4ANaUhMdjmRa6arXtqBcXIyUvu//5e80nlXekqMKaW7f5wrLNiKZB+ck7ayGlI1NYLNQ5nCWC6Xxe6s="
  secret_access_key:
    secure: "Jn9clQh78C2c1zoueTkn0r5kSCHrbb7bMojb8/Ne+6zg0pD/3w25mrhEC4y9b3M/lHoKArOPj4dn03ZErJleM8aOMNMIa6ck8GKP+7EoFlZ/1/C5733HazlldTWDd2+wTOYfSIGOM+mHDP5tmK0S7pr1zEm+/++UExuGZXiCSSI="
  bucket: travis-build-examples
  local-dir: examples
  skip-cleanup: true
  endpoint: travis-build-examples.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  on:
    branch: master
    condition: $INTEGRATION_SPECS == 1
